[colors.primary]
background = "0x181818"
foreground = "0xe0e0e0"

[font]
size = 13.0

[font.normal]
family = "ProFontWindows"
style = "Regular"

[window]
opacity = 0.98
decorations = "None"
dynamic_padding = true

[window.padding]
x = 25
y = 25
