#!/usr/bin/env zsh

# dmenu to change runstate using systemd
Location='$HOME/.scripts/dmenu_script/tool'

# menu defined as an associative array
typeset -A menu
menu=(
[Network]="$Location/dmenu_network"
[Device]="$Location/dmenu_usb"
[Screen]="lxrandr"
[Sound]="pavucontrol"
[Bluetooth]="$Location/start_bluetooth"
[Cancel]=""
)
menu_nrows=${#menu[@]}
menu_list="Network\nDevice\nScreen\nSound\nBluetooth\nCancel\n"

Selection=$(echo -e ${menu_list} | dmenu -b -i -nb '#151515' -nf '#e0e0e0' -sb '#e0e0e0' -sf '#151515' -fn 'ProFontWindows:style=regular:size=12')
zsh -c "exec ${menu[${Selection}]}" && kill $POD
