#!/bin/sh
#i3lockpath=/usr/bin/i3lock 

DISPLAY_RE="([0-9]+)x([0-9]+)\\+([0-9]+)\\+([0-9]+)" # Regex to find display dimensions
FOLDER=`dirname "$BASH_SOURCE"` # Current folder
CACHE_FOLDER="$FOLDER"/tmp/ # Cache folder
if ! [ -e $CACHE_FOLDER ]; then
    mkdir $CACHE_FOLDER
fi

#Image paths
    BKG_IMG=$HOME/.wallpaper/dimmed

if ! [ -e "$BKG_IMG" ]; then
    echo "No background image! Exiting..."
    exit 2
fi

MD5_BKG_IMG=$(md5sum $BKG_IMG | cut -c 1-10)
MD5_SCREEN_CONFIG=$(xrandr | md5sum - | cut -c 1-32) # Hash of xrandr output
OUTPUT_IMG="$CACHE_FOLDER""$MD5_SCREEN_CONFIG"."$MD5_BKG_IMG".png # Path of final image
OUTPUT_IMG_WIDTH=0 # Decide size to cover all screens
OUTPUT_IMG_HEIGHT=0 # Decide size to cover all screens

#i3lock command
LOCK_BASE_CMD="i3lock -i $OUTPUT_IMG"
if [ "$lock_args" ]; then
        LOCK_ARGS="$lock_args"  # Passed command
else
        LOCK_ARGS="-t -e"  # Default
fi
LOCK_CMD="$LOCK_BASE_CMD $LOCK_ARGS"

if ! [ -e $OUTPUT_IMG ]
then
	while read LINE
	do
		#If we are reading the line that contains the position information:
		if [[ $LINE =~ $DISPLAY_RE ]]; then
			#Extract information and append some parameters to the ones that will be given to ImageMagick:
			SCREEN_WIDTH=${BASH_REMATCH[1]}
			SCREEN_HEIGHT=${BASH_REMATCH[2]}
			SCREEN_X=${BASH_REMATCH[3]}
			SCREEN_Y=${BASH_REMATCH[4]}

			CACHE_IMG="$CACHE_FOLDER""$SCREEN_WIDTH"x"$SCREEN_HEIGHT"."$MD5_BKG_IMG".png
			## if cache for that screensize doesnt exist
			if ! [ -e $CACHE_IMG ]
			then
				# Create image for that screensize
				eval convert '$BKG_IMG' '-resize' '${SCREEN_WIDTH}X${SCREEN_HEIGHT}^' '-gravity' 'Center' '-crop' '${SCREEN_WIDTH}X${SCREEN_HEIGHT}+0+0' '+repage' '$CACHE_IMG'
			fi

			# Decide size of output image
			if (( $OUTPUT_IMG_WIDTH < $SCREEN_WIDTH+$SCREEN_X )); then OUTPUT_IMG_WIDTH=$(($SCREEN_WIDTH+$SCREEN_X)); fi;
				if (( $OUTPUT_IMG_HEIGHT < $SCREEN_HEIGHT+$SCREEN_Y )); then OUTPUT_IMG_HEIGHT=$(( $SCREEN_HEIGHT+$SCREEN_Y )); fi;

					PARAMS="$PARAMS $CACHE_IMG -geometry +$SCREEN_X+$SCREEN_Y -composite "
				fi
			done <<<"`xrandr`"

			#Execute ImageMagick:
			eval convert -size ${OUTPUT_IMG_WIDTH}x${OUTPUT_IMG_HEIGHT} 'xc:black' $OUTPUT_IMG
			eval convert $OUTPUT_IMG $PARAMS $OUTPUT_IMG
		fi
#Lock the screen:
$LOCK_CMD

################################################################################

#$i3lockpath 
#i3lock -u -c 000000

#i3lock -u -i $HOME/.wallpaper/dimmed
#i3lockpid=$(pgrep -f i3lock | head -n 1)
#sleep 0.5

winid=`xwininfo -name "i3lock" | grep "Window id" | grep -oE "0x[0-9a-f]+"`
if [ -z "$winid" ]
then
    echo "Could not find i3lock window"
    exit 1
fi

conky -c ~/.config/conky/lock.conf -w "$winid" &
conkypid=$!

#echo "HERE ${i3lockpid}"
#echo "HERE ${conkypid}"

while pgrep i3lock > /dev/null;
do
	sleep 0.1;
done
kill $conkypid
#pkill conky
